# 当有改动推送到master分支时，启动Action
name: 自动部署

on:
  push:
    branches:
      - master

  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查分支
        uses: actions/checkout@v2

      - name: 安装 Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: 安装模块
        run: |
          pip install -r requirements.txt

      - name: 生成json文件
        run: |
          export TZ='Asia/Shanghai'
          python build_linux.py

      - name: 暂存提交
        run: |
          git config --global user.name 'evrstr'
          git config --global user.email '429427989@qq.com'
          export TZ='Asia/Shanghai'
          git add .
          git commit -m "update" -a

      - name: 推送
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
